[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Serial Monitor options
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; Build options
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_RUNNING_CORE=1
    -DARDUINO_EVENT_RUNNING_CORE=1
    -DTF_LITE_STATIC_MEMORY
    -DTF_LITE_MCU_DEBUG_LOG
    -O2

; Partition scheme
board_build.partitions = huge_app.csv
board_build.arduino.memory_type = qio_opi

; Library dependencies
lib_deps = 
    https://github.com/tensorflow/tflite-micro-arduino-examples
    https://github.com/espressif/esp-dsp.git

; Upload options
upload_speed = 921600
upload_port = /dev/ttyUSB0

; Monitor options  
monitor_port = /dev/ttyUSB0 